mutation ($fromTierId: Int!, $toTierId: Int!) {
  membership {
    bulkMigrateUsers(fromTierId: $fromTierId, toTierId: $toTierId) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
