query {
  theming {
    themes {
      key
      title
      author
    }
    config {
      theme
      iconset
      darkMode
      tocPosition
      showTags
      showReturnToTop
      injectCSS
      injectHead
      injectBody
    }
  }
}
