mutation($id: Int, $slug: String, $locale: String) {
  pages {
    delete(id: $id, slug: $slug, locale: $locale) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
