query ($query: String!, $locale: String) {
  pages {
    search(query:$query, locale:$locale) {
      results {
        id
        title
        description
        path
        locale
        tags
      }
      suggestions
      totalHits
    }
  }
}
